name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install criterion

      - name: Run tests
        run: gcc tests/unit.c lib/*.c -I/opt/homebrew/include -L/opt/homebrew/lib -lcriterion && ./a.out

  check:
    name: Check

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download actionlint
        id: actionlint
        run: bash <(curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

      - name: Install dependencies
        run: brew install ripgrep prettier clang-format

      - name: Format
        run: |
          clang-format --dry-run --Werror main.c lib/*.c
          prettier --check .

      - name: Check for forbidden words
        run: ./bin/forbid

  pages:
    name: Pages

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install emscripten

      - name: Build WASM
        run: |
          emcc lib/*.c \
            -s EXPORTED_FUNCTIONS="['_malloc', '_free']" \
            -s EXPORTED_RUNTIME_METHODS="['ccall', 'stringToUTF8', 'UTF8ToString']" \
            -s WASM=1 \
            -o www/index.js

      - name: Record Git Revision
        run: git rev-parse --verify HEAD > www/commit.txt

      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{secrets.PAT}}
          publish_branch: gh-pages
          publish_dir: www
